### ISSUE TITLE
Valores por defecto incorrectos

### ISSUE THREAD

**Issue by Sophivorus** [datos-justicia-argentina/Base-de-datos-legislativos-infoleg#2]
Hola! Estos días estuve trabajando con los datos de Infoleg y noté que muchísimas normativas (por ejemplo las leyes 1, 2, 3, 4, etc.) tienen `fecha_boletin` igual a `24/05/1810`, `numero_boletin` igual a `0` y `pagina_boletin` igual a `0`. Es probable que estos sean los valores por defecto cuando falta información, pero si es así, entonces creo que sería mejor y más correcto dejar los valores en blanco, ya que de lo contrario puede llevar a confusiones y obliga a las aplicaciones que utilicen los datos (como la que estoy desarrollando) a poner condicionales del tipo:

    if ( fecha_boletin === "24/05/1810" ) {
        fecha_boletin = null;
    }

También el campo `clase_norma` tiene como valor por defecto una cadena de caracteres compuesta de **un espacio**, pero probablemente debería tener una cadena de caracteres vacía. Este detalle hasta ahora no me causa problemas, pero a otros podría traer complicaciones difíciles de debuggear.

**Comment by jsadi** [comment]
Hola! Estamos trabajando en estas sugerencias. Saludos!

**Comment by Sophivorus** [comment]
Acabo de bajar la última versión y me alegra ver que adoptaron todas las sugerencias, ¡gracias!

Aprovecho para señalar un par de cuestiones similares que acabo de notar (no sé si estaban presentes antes):
- El campo "observaciones" parece tener como valor por defecto una cadena de caracteres compuesto por **un espacio**, en vez de una cadena de caracteres vacía
- El campo "modifica_a" parece tener como valor por defecto una cadena de caracteres vacía, en vez de "0" como el campo "modificada_por"

Espero que les sirva, ¡gracias otra vez!

**Comment by Sophivorus** [comment]
Hola! Un par de observaciones más en torno a los valores por defecto de la versión actual del dataset:

* El campo "texto_actualizado", cuando no está vacío, contiene el valor "http://ser" y en ningún caso contiene una URL válida
* El campo "organismo_origen" está vacío siempre, pero en versiones previas del dataset había muchas normas para las cuales no estaba vacío

Más allá de estos detalles, no quiero dejar de agradecer el dataset, ¡me es muy útil!

**Comment by jsadi** [comment]
Hola Sophivorus, respecto del campo "texto_actualizado" verifiqué que siempre tiene datos completos o vacíos, el valor "http://ser" es lo que muestra en pantalla por el ancho de columna estandard del visualizador. Si la ensanchas vas a ver el link completo. Si ves que esto no es así por favor pasame alguna de las normas en la cuales te pasa esto para hacer seguimiento.
Respecto de "organismo_origen" estamos mirando qué paso. En cuanto encontremos la causa del bug subimos los datos correctos.
Saludos y gracias por avisar!

**Comment by Sophivorus** [comment]
Hola, gracias por la rápida respuesta. Volví a bajar la base y las URLs del campo "texto_actualizado" están perfectas, no se qué habrá pasado.

Por otra parte, abrí el CSV en un editor de texto, hice una búsqueda de espacios vacíos " " y parece que todavía quedan algunos. No es que sea grave pero pueden causar bugs, quizás los quieran quitar.

De nuevo, gracias por el dataset!

**Comment by jsadi** [comment]
Hola, ya están solucionados los dos inconvenientes: los datos de organismo origen y los espacios vacíos en url.
Saludos!

**Comment by Sophivorus** [comment]
Genial, gracias! Ya no detecto más errores en los valores por defecto, así que doy por cerrado este issue, hasta la próxima!
