### ISSUE TITLE
404 al intentar descargar el dataset

### ISSUE THREAD

**Issue by Sophivorus** [datos-justicia-argentina/Base-de-datos-legislativos-infoleg#3]
Hola! Hace unos días noté que al intentar descargar el dataset desde http://datos.jus.gob.ar/dataset/base-de-datos-legislativos-infoleg me tira 404!!!

Estoy utilizando los datos que ustedes publican para generar un sitio de legislación que está por salir a la luz, por favor vuelvan! Gracias XD

**Comment by jsadi** [comment]
Hola, puede ser que te hayan quedado las urls desactualizadas, porque tuvimos que eliminar los recursos y volver a crearlos. Te paso las url actuales:
[Base infoleg Normativa Nacional](http://datos.jus.gob.ar/dataset/base-de-datos-legislativos-infoleg/archivo/8b1c2310-564e-41e6-9a84-99cfa9939bbc)
[Base Complementaria Infoleg de Normas Modificadas](http://datos.jus.gob.ar/dataset/base-de-datos-legislativos-infoleg/archivo/ae4babf3-164c-4726-bc58-8ff1c192afab)
[Base Complementaria Infoleg de Normas Modificatorias](http://datos.jus.gob.ar/dataset/base-de-datos-legislativos-infoleg/archivo/1092c0b4-3be5-41dd-bc72-feba592afcdf)
