### ISSUE TITLE
Campo titulo_sumario

### ISSUE THREAD

**Issue by perezzini** [datos-justicia-argentina/Base-de-datos-legislativos-infoleg#5]
Hola,

Me preguntaba cuál es el rol del campo `titulo_sumario`. Dado que es posible observar a simple vista la repetición de valores... es acaso el mencionado campo un conjunto de categorías (clases)? Y si lo fuese, nuevamente, cuál es su significado en particular?

Gracias de antemano!

**Comment by jsadi** [comment]
Hola perezzini, en "Base Infoleg Normativa Nacional", titulo_sumario refiere al tema genérico de la norma. A saber, "Acceso a la información pública", "Hidrocarburos", "Convenciones colectivas de trabajo", etc. Es una clasificación. Aunque, como se trata de una base que se fue alimentando a lo largo del tiempo una misma categoría puede estar expresada de distintas formas (por ejemplo, "Ablación e implante", pero también "Ablación e implantes de órganos"). 
Hay algunos pocos casos coinciden los campos titulo_sumario y titulo_resumido. Por ejemplo, en "condecoraciones". 
Espero haber solucionado tus dudas.
Saludos!

**Comment by perezzini** [comment]
Hola, @jsadi 

Gracias por responder. Entonces lo tomo como un conjunto de categorías teniendo en cuenta algunas salvedades de diferencias de escritura.

Cualquier cosa, me comentás! Gracias, nuevamente.
